# Generated by Django 4.1.1 on 2022-09-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_body_book_description_book_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='tag',
            new_name='genre',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
